spring.application.name=ApiGateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
api-gateway.message = Api Gateway  is running from config server


# Route 1 - User Service
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://UserService
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

# Route 2 - Doctor Service
spring.cloud.gateway.server.webflux.routes[1].id=doctor-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://DoctorService
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/doctors/**

logging.level.org.springframework.cloud.gateway=DEBUG

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
